# Stage 1: Build the application
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY pom.xml ./
COPY src ./src
RUN mvn clean package

# Stage 2: Run the application
FROM openjdk:17.0.2-jdk-oracle
WORKDIR /app
COPY --from=build /app/target/spring-rabbitmq-producer-0.0.1-SNAPSHOT.jar ./producer.jar
CMD ["java", "-jar", "producer.jar"]